name: Terraform Deploy

on:
  push:
    branches:
      - main
      - prod

jobs:

  terraform-plan:
    runs-on: ubuntu-latest
    environment: AWS_Credentials

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Select tfvars
        id: vars
        run: |
          case "${GITHUB_REF_NAME}" in 
            main)
              echo "tfvars=env/dev.tfvars" >> $GITHUB_OUTPUT ;;
            prod) 
              echo "tfvars=env/prod.tfvars" >> $GITHUB_OUTPUT ;;
            *)
              echo "Unsupported branch" 
              exit 1 
              ;;
          esac

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file=${{ steps.vars.outputs.tfvars }}